-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- local km = vim.keymap
-- --- Moving line mapping
-- km.set("n", "J", ":m .+1<CR>")
-- km.set("n", "K", ":m .-2<CR>")
-- -- moving multiple line mapping
-- km.set("v", "K", ":m '<-2<CR>gv=gv")
-- km.set("v", "J", ":m '>+1<CR>gv=gv")
